//! C header generation - migration step 3 (DESIGN.md §6).
//!
//! Generates the *data* halves of the analyzer's tables from database/:
//!
//!   analyzer/lookup.h                  - whole file (it is all data)
//!   analyzer/physicalquantity-data.h   - PhysicalQuantity statics + list
//!   analyzer/fieldtype-data.h          - fieldTypeList[]
//!   analyzer/pgn-data.h                - pgnList[]
//!
//! The hand-written halves (structs, macros, prototypes) stay in pgn.h /
//! fieldtype.h, which #include the data files inside their GLOBALS blocks.
//! pgn-j1939.h is untouched (self-contained macro set, hand-written data).
//!
//! Emission philosophy: pure designated initializers, no field macro zoo.
//! Values are emitted authored-or-default exactly as the pgn.h macros would
//! have set them, so fillFieldType() resolves to identical runtime tables -
//! proven by the step-3 gate: the OLD C XML path (analyzer-explain) over the
//! generated headers must reproduce docs/canboat.xml byte-for-byte, and the
//! analyzer test suite must pass.

use crate::derive::default_field_resolution;
use crate::model::{Database, Field, FieldType, Interval, Pgn};

const BANNER: &str = "/* GENERATED BY keel FROM database/ - DO NOT EDIT.\n\
 *\n\
 * (C) 2009-2026, Kees Verruijt, Harlingen, The Netherlands.\n\
 * Part of CANboat; licensed under the Apache License, Version 2.0.\n\
 */\n\n";

fn c_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Shortest round-trip double literal; C parses it back to the same f64.
fn c_double(v: f64) -> String {
    format!("{v:?}")
}

fn sentinel_symbol(name: &str) -> &'static str {
    match name {
        "TopOfRange" => "SENTINEL_TOP_OF_RANGE",
        "NaN" => "SENTINEL_NAN",
        "EmptyString" => "SENTINEL_EMPTY_STRING",
        "Variable" => "SENTINEL_VARIABLE",
        _ => "SENTINEL_NONE",
    }
}

// ---------------------------------------------------------------------------
// lookup.h
// ---------------------------------------------------------------------------

const LOOKUP_PROLOGUE: &str = r#"
#ifndef LOOKUP_TYPE
#define LOOKUP_TYPE(a, b)
#endif
#ifndef LOOKUP_TYPE_TRIPLET
#define LOOKUP_TYPE_TRIPLET(a, b)
#endif
#ifndef LOOKUP_TYPE_BITFIELD
#define LOOKUP_TYPE_BITFIELD(a, b)
#endif
#ifndef LOOKUP_TYPE_FIELDTYPE
#define LOOKUP_TYPE_FIELDTYPE(a, b)
#endif
#ifndef LOOKUP
#define LOOKUP(a, b, c)
#endif
#ifndef LOOKUP_TRIPLET
#define LOOKUP_TRIPLET(a, b, c, d)
#endif
#ifndef LOOKUP_BITFIELD
#define LOOKUP_BITFIELD(a, b, c)
#endif
#ifndef LOOKUP_FIELDTYPE
#define LOOKUP_FIELDTYPE(a, b, c, d)
#endif
#ifndef LOOKUP_FIELDTYPE_LOOKUP
#define LOOKUP_FIELDTYPE_LOOKUP(a, b, c, d, e, f, g)
#endif
#ifndef LOOKUP_END
#define LOOKUP_END
#endif
"#;

const LOOKUP_EPILOGUE: &str = "// Keep this at the end, so a next include does not need to do this
#undef LOOKUP_TYPE
#undef LOOKUP_TYPE_TRIPLET
#undef LOOKUP_TYPE_BITFIELD
#undef LOOKUP_TYPE_FIELDTYPE
#undef LOOKUP
#undef LOOKUP_TRIPLET
#undef LOOKUP_BITFIELD
#undef LOOKUP_FIELDTYPE
#undef LOOKUP_FIELDTYPE_LOOKUP
#undef LOOKUP_END
";

pub fn emit_lookup_h(db: &Database) -> String {
    let mut out = String::with_capacity(256 << 10);
    out.push_str(BANNER);
    out.push_str(LOOKUP_PROLOGUE);
    out.push('\n');

    for lk in db.ordered_lookups("pair") {
        out.push_str(&format!("LOOKUP_TYPE({}, BITS({}))\n", lk.name, lk.bits));
        for (value, name) in &lk.pairs {
            out.push_str(&format!("LOOKUP({}, {value}, {})\n", lk.name, c_str(name)));
        }
        out.push_str("LOOKUP_END\n\n");
    }
    for lk in db.ordered_lookups("triplet") {
        out.push_str(&format!(
            "LOOKUP_TYPE_TRIPLET({}, BITS({}))\n",
            lk.name, lk.bits
        ));
        for (v1, v2, name) in &lk.triplets {
            out.push_str(&format!(
                "LOOKUP_TRIPLET({}, {v1}, {v2}, {})\n",
                lk.name,
                c_str(name)
            ));
        }
        out.push_str("LOOKUP_END\n\n");
    }
    for lk in db.ordered_lookups("bit") {
        out.push_str(&format!(
            "LOOKUP_TYPE_BITFIELD({}, BITS({}))\n",
            lk.name, lk.bits
        ));
        for (bit, name) in &lk.pairs {
            out.push_str(&format!(
                "LOOKUP_BITFIELD({}, {bit}, {})\n",
                lk.name,
                c_str(name)
            ));
        }
        out.push_str("LOOKUP_END\n\n");
    }
    for lk in db.ordered_lookups("fieldtype") {
        out.push_str(&format!(
            "LOOKUP_TYPE_FIELDTYPE({}, BITS({}))\n",
            lk.name, lk.bits
        ));
        for e in &lk.fieldtypes {
            let ft = &db.fieldtypes[db.fieldtype(&e.fieldtype).expect("checked")];
            match &e.lookup {
                Some(nested) => {
                    let bits = e.bits.unwrap_or(ft.size);
                    let kind = e.lookup_kind.as_deref().unwrap_or("pair").to_uppercase();
                    out.push_str(&format!(
                        "LOOKUP_FIELDTYPE_LOOKUP({}, {}, {}, {}, {bits}, {kind}, {nested})\n",
                        lk.name,
                        e.value,
                        c_str(&e.name),
                        c_str(&e.fieldtype)
                    ));
                }
                None => {
                    out.push_str(&format!(
                        "LOOKUP_FIELDTYPE({}, {}, {}, {})\n",
                        lk.name,
                        e.value,
                        c_str(&e.name),
                        c_str(&e.fieldtype)
                    ));
                }
            }
        }
        out.push_str("LOOKUP_END\n\n");
    }

    out.push_str(LOOKUP_EPILOGUE);
    out
}

// ---------------------------------------------------------------------------
// physicalquantity-data.h
// ---------------------------------------------------------------------------

pub fn emit_physicalquantity_data_h(db: &Database) -> String {
    let mut out = String::with_capacity(16 << 10);
    out.push_str(BANNER);
    for pq in &db.physical_quantities {
        out.push_str(&format!("static const PhysicalQuantity {} = {{\n", pq.name));
        out.push_str(&format!("    .name = {},\n", c_str(&pq.name)));
        if let Some(v) = &pq.description {
            out.push_str(&format!("    .description = {},\n", c_str(v)));
        }
        if let Some(v) = &pq.comment {
            out.push_str(&format!("    .comment = {},\n", c_str(v)));
        }
        if let Some(v) = &pq.unit {
            out.push_str(&format!("    .abbreviation = {},\n", c_str(v)));
        }
        if let Some(v) = &pq.unit_description {
            out.push_str(&format!("    .unit = {},\n", c_str(v)));
        }
        if let Some(v) = &pq.url {
            out.push_str(&format!("    .url = {},\n", c_str(v)));
        }
        out.push_str("};\n\n");
    }
    out.push_str("const PhysicalQuantity *const PhysicalQuantityList[] = {\n");
    for pq in &db.physical_quantities {
        out.push_str(&format!("    &{},\n", pq.name));
    }
    out.push_str("    NULL,\n};\n");
    out
}

// ---------------------------------------------------------------------------
// fieldtype-data.h
// ---------------------------------------------------------------------------

/// Emitted from the AUTHORED fieldtype attributes (pre-percolation), exactly
/// like the hand-written initializers: fillFieldType() re-derives the rest.
pub fn emit_fieldtype_data_h(authored: &[FieldType]) -> String {
    let mut out = String::with_capacity(64 << 10);
    out.push_str(BANNER);
    out.push_str("FieldType fieldTypeList[] = {\n");
    for ft in authored {
        out.push_str("    {");
        let mut parts: Vec<String> = vec![format!(".name = {}", c_str(&ft.name))];
        if let Some(v) = &ft.description {
            parts.push(format!(".description = {}", c_str(v)));
        }
        if let Some(v) = &ft.encoding_description {
            parts.push(format!(".encodingDescription = {}", c_str(v)));
        }
        if let Some(v) = &ft.comment {
            parts.push(format!(".comment = {}", c_str(v)));
        }
        if let Some(v) = &ft.url {
            parts.push(format!(".url = {}", c_str(v)));
        }
        if ft.size != 0 {
            parts.push(format!(".size = {}", ft.size));
        }
        if ft.variable_size {
            parts.push(".variableSize = True".into());
        }
        if let Some(v) = &ft.base {
            parts.push(format!(".baseFieldType = {}", c_str(v)));
        }
        if let Some(v) = &ft.unit {
            parts.push(format!(".unit = {}", c_str(v)));
        }
        if ft.offset != 0 {
            parts.push(format!(".offset = {}", ft.offset));
        }
        if ft.resolution != 0.0 {
            parts.push(format!(".resolution = {}", c_double(ft.resolution)));
        }
        if let Some(s) = ft.has_sign {
            parts.push(format!(".hasSign = {}", if s { "True" } else { "False" }));
        }
        if ft.sentinels != "None" {
            parts.push(format!(".sentinels = {}", sentinel_symbol(&ft.sentinels)));
        }
        if let Some(v) = &ft.physical {
            parts.push(format!(".physical = &{v}"));
        }
        if let Some(v) = &ft.print_function {
            parts.push(format!(".pf = {v}"));
        }
        if let Some(v) = ft.range_min_authored {
            parts.push(format!(".rangeMin = {}", c_double(v)));
        }
        if let Some(v) = ft.range_max_authored {
            parts.push(format!(".rangeMax = {}", c_double(v)));
        }
        out.push_str(&parts.join(",\n     "));
        out.push_str("},\n\n");
    }
    out.push_str("};\n");
    out
}

// ---------------------------------------------------------------------------
// pgn-data.h
// ---------------------------------------------------------------------------

fn complete_expr(pgn: &Pgn) -> String {
    // The Interval bit is derived at runtime (fieldtype.c:486), never emitted.
    let mut bits: Vec<&str> = Vec::new();
    for m in &pgn.missing {
        bits.push(match m.as_str() {
            "Fields" => "PACKET_FIELDS_UNKNOWN",
            "FieldLengths" => "PACKET_FIELD_LENGTHS_UNKNOWN",
            "Resolution" => "PACKET_RESOLUTION_UNKNOWN",
            "Lookups" => "PACKET_LOOKUPS_UNKNOWN",
            "SampleData" => "PACKET_NOT_SEEN",
            "MissingCompanyFields" => "PACKET_MISSING_COMPANY_FIELDS",
            _ => continue,
        });
    }
    if bits.is_empty() {
        "PACKET_COMPLETE".into()
    } else {
        bits.join(" | ")
    }
}

fn packet_type_symbol(t: &str) -> &'static str {
    match t {
        "Fast" => "PACKET_FAST",
        "ISO" => "PACKET_ISO_TP",
        "Mixed" => "PACKET_MIXED",
        _ => "PACKET_SINGLE",
    }
}

fn emit_field(db: &Database, f: &Field) -> String {
    let ft = &db.fieldtypes[f.ft];
    // camelName (the frozen <Id>) is explicit on every field, like the YAML;
    // analyzer.c keys naming decisions on the showCamel mode, never on
    // camelName presence.
    let mut parts: Vec<String> = vec![
        format!(".name = {}", c_str(&f.name)),
        format!(".camelName = {}", c_str(&f.id)),
        format!(".fieldType = {}", c_str(&f.type_)),
    ];
    if let Some(bits) = f.bits {
        parts.push(format!(".size = {bits}"));
    }
    // resolution: what the pgn.h macro would have set - authored, or the
    // per-root default when the fieldtype carries no resolution of its own
    // (fillFieldType inherits the fieldtype's when we emit nothing).
    if let Some(r) = f.resolution {
        parts.push(format!(".resolution = {}", c_double(r)));
    } else if ft.resolution == 0.0 {
        let d = default_field_resolution(&ft.root_name);
        if d != 0.0 {
            parts.push(format!(".resolution = {}", c_double(d)));
        }
    }
    if ft.has_sign == Some(true) {
        parts.push(".hasSign = true".into());
    }
    if let Some(m) = &f.match_ {
        parts.push(format!(".unit = {}", c_str(&format!("={m}"))));
    } else if let Some(u) = &f.unit {
        parts.push(format!(".unit = {}", c_str(u)));
    }
    if let Some(o) = f.offset {
        parts.push(format!(".offset = {o}"));
    }
    if let Some(d) = &f.description {
        parts.push(format!(".description = {}", c_str(d)));
    }
    if let Some((kind, name)) = f.lookup_ref() {
        let (type_sym, member) = match kind {
            "triplet" => ("LOOKUP_TYPE_TRIPLET", "LOOKUP_TRIPLET_MEMBER"),
            "bit" => ("LOOKUP_TYPE_BIT", "LOOKUP_BIT_MEMBER"),
            "fieldtype" => ("LOOKUP_TYPE_FIELDTYPE", "LOOKUP_FIELDTYPE_MEMBER"),
            _ => ("LOOKUP_TYPE_PAIR", "LOOKUP_PAIR_MEMBER"),
        };
        parts.push(format!(".lookup.type = {type_sym}"));
        parts.push(format!("{member} = lookup{name}"));
        parts.push(format!(".lookup.name = {}", c_str(name)));
        if let Some(order) = f.lookup_indirect_order {
            parts.push(format!(".lookup.val1Order = {order}"));
        }
    } else if ft.root_name == "LOOKUP" {
        // UNKNOWN_LOOKUP_FIELD: lookup type without an enumeration
        parts.push(".lookup.type = LOOKUP_TYPE_PAIR".into());
    }
    if f.proprietary {
        parts.push(".proprietary = true".into());
    }
    if f.primary_key {
        parts.push(".partOfPrimaryKey = true".into());
    }
    if let Some(sv) = f.special_values {
        parts.push(format!(".reservedOverride = {}", sv + 1));
    }
    if f.dynamic_field_length {
        parts.push(".dynamicFieldLength = true".into());
        if f.dynamic_field_length_overhead != 0 {
            parts.push(format!(
                ".dynamicFieldLengthOverhead = {}",
                f.dynamic_field_length_overhead
            ));
        }
    }
    if let Some(v) = f.range_min {
        parts.push(format!(".rangeMin = {}", c_double(v)));
    }
    if let Some(v) = f.range_max {
        parts.push(format!(".rangeMax = {}", c_double(v)));
    }
    format!("      {{{}}}", parts.join(", "))
}

fn emit_pgn(db: &Database, p: &Pgn) -> String {
    let mut out = String::with_capacity(2 << 10);
    out.push_str(&format!(
        "    {{{},\n     {},\n     {},\n     {},\n     {{\n",
        c_str(&p.description),
        p.pgn,
        complete_expr(p),
        packet_type_symbol(&p.type_)
    ));
    let fields: Vec<String> = p.fields.iter().map(|f| emit_field(db, f)).collect();
    out.push_str(&fields.join(",\n"));
    out.push_str("\n     },\n");

    let mut named: Vec<String> = vec![format!(".camelDescription = {}", c_str(&p.id))];
    if p.fallback {
        named.push(".fallback = true".into());
    }
    match p.interval {
        Interval::Ms(ms) if ms != 0 => named.push(format!(".interval = {ms}")),
        Interval::Irregular => named.push(".interval = UINT16_MAX".into()),
        _ => {}
    }
    if p.priority != 0 {
        named.push(format!(".priority = {}", p.priority));
    }
    for (n, rep) in [(1, &p.repeating1), (2, &p.repeating2)] {
        if let Some(rep) = rep {
            if rep.count > 0 {
                named.push(format!(".repeatingCount{n} = {}", rep.count));
                named.push(format!(".repeatingStart{n} = {}", rep.start));
                named.push(format!(
                    ".repeatingField{n} = {}",
                    rep.count_field.unwrap_or(255)
                ));
            }
        }
    }
    if let Some(v) = &p.explanation {
        named.push(format!(".explanation = {}", c_str(v)));
    }
    if let Some(v) = &p.url {
        named.push(format!(".url = {}", c_str(v)));
    }
    if let Some(v) = &p.research_doc {
        named.push(format!(".researchDoc = {}", c_str(v)));
    }
    out.push_str(&format!("     {}}}", named.join(",\n     ")));
    out
}

pub fn emit_pgn_data_h(db: &Database, j1939: bool) -> String {
    let list = if j1939 { &db.pgns_j1939 } else { &db.pgns };
    let mut out = String::with_capacity(2 << 20);
    out.push_str(BANNER);
    out.push_str("Pgn pgnList[] = {\n");
    let pgns: Vec<String> = list.iter().map(|p| emit_pgn(db, p)).collect();
    out.push_str(&pgns.join(",\n\n"));
    out.push_str("\n};\n");
    out
}
