/*

Analyzes NMEA 2000 PGNs.

(C) 2009-2021, Kees Verruijt, Harlingen, The Netherlands.

This file is part of CANboat.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

/* https://www.nmea.org/Assets/20190623%20manu%20code%20and%20product%20code.pdf */

COMPANY("Actia", 199)
COMPANY("Actisense", 273)
COMPANY("Advansea", 578)
COMPANY("AEM Power", 735)
COMPANY("Aetna Engineering/Fireboy/Xintex", 215)
COMPANY("Airmar", 135)
COMPANY("Alltek Marine Electronics Corp", 459)
COMPANY("Amphenol LTW Technology", 274)
COMPANY("Aquatic AV", 600)
COMPANY("ARKS Enterprises, Inc.", 69)
COMPANY("Arlt Tecnologies", 614)
COMPANY("ASA Electronics", 905)
COMPANY("Attwood Marine", 502)
COMPANY("Au Electronics Group", 735)
COMPANY("Autonnic", 715)
COMPANY("Aventics GmbH", 605)
COMPANY("Bavaria Yacts", 637)
COMPANY("Beede Instruments", 185)
COMPANY("BEP Marine", 116)
COMPANY("BEP Marine", 295)
COMPANY("Beyond Measure", 396)
COMPANY("B & G", 381)
COMPANY("BJ Technologies (Beneteau)", 802)
COMPANY("Blue Seas", 969)
COMPANY("Blue Water Data", 148)
COMPANY("Blue Water Desalination", 811)
COMPANY("Böning Automationstechnologie GmbH & Co. KG", 341)
COMPANY("Broyda Industries", 795)
COMPANY("Camano Light", 384)
COMPANY("Canadian Automotive", 796)
COMPANY("Capi 2", 394)
COMPANY("Carling Technologies Inc. (Moritz Aerospace)", 176)
COMPANY("Chetco Digitial Instruments", 481)
COMPANY("Clarion US", 773)
COMPANY("Coelmo SRL Italy", 286)
COMPANY("Comar Systems Limited", 438)
COMPANY("ComNav", 404)
COMPANY("Cox Powertrain", 968)
COMPANY("CPAC Systems AB", 165)
COMPANY("Cummins", 440)
COMPANY("DaeMyung", 743)
COMPANY("Data Panel Corp", 868)
COMPANY("Dief", 329)
COMPANY("Digital Switching Systems", 211)
COMPANY("Digital Yacht", 437)
COMPANY("Disenos Y Technologia", 201)
COMPANY("Diverse Yacht Services", 641)
COMPANY("Ecotronix", 930)
COMPANY("Egersund Marine Electronics AS", 426)
COMPANY("Electronic Design", 373)
COMPANY("EMMI NETWORK S.L.", 224)
COMPANY("Empir Bus", 304)
COMPANY("em-trak Marine Electronics", 427)
COMPANY("Eride", 243)
COMPANY("Evinrude/BRP", 163)
COMPANY("Faria Instruments", 1863)
COMPANY("Fell Marine", 844)
COMPANY("Fischer Panda", 311)
COMPANY("Fischer Panda DE", 785)
COMPANY("Fischer Panda Generators", 356)
COMPANY("FLIR", 815)
COMPANY("Floscan Instrument Co. Inc.", 192)
COMPANY("Furuno", 1855)
COMPANY("Fusion Electronics", 419)
COMPANY("FW Murphy/Enovation Controls", 78)
COMPANY("Garmin", 229)
COMPANY("Garmin", 645)
COMPANY("GeoNav", 385)
COMPANY("Gill Sensors", 803)
COMPANY("Glendinning", 378)
COMPANY("GME aka Standard Communications Pty LTD", 475)
COMPANY("Groco", 272)
COMPANY("Hamilton Jet", 283)
COMPANY("Hemisphere GPS Inc", 88)
COMPANY("HMI Systems", 776)
COMPANY("Honda Marine", 175)
COMPANY("Honda Marine", 200)
COMPANY("Honda Marine", 225)
COMPANY("Honda Marine", 250)
COMPANY("Honda Motor Company LTD", 140)
COMPANY("Honda Motor Company LTD", 257)
COMPANY("Humminbird Marine Electronics", 467)
COMPANY("Humminbird Marine Electronics", 476)
COMPANY("ICOM", 315)
COMPANY("Intellian", 606)
COMPANY("Japan Radio Co", 1853)
COMPANY("JL Audio", 704)
COMPANY("Johnson Outdoors Marine Electronics Inc Geonav", 385)
COMPANY("Kohler Power Systems", 85)
COMPANY("Korean Maritime University", 345)
COMPANY("Kvasar", 743)
COMPANY("Kvasar AB", 1859)
COMPANY("KVH", 579)
COMPANY("L3 Technologies", 890)
COMPANY("Lcj Capteurs", 499)
COMPANY("Litton", 1858)
COMPANY("Livorsi Marine", 400)
COMPANY("Lowrance", 140)
COMPANY("Lumishore", 798)
COMPANY("LxNav", 739)
COMPANY("Maretron", 137)
COMPANY("Marinecraft (South Korea)", 571)
COMPANY("Marines Co (South Korea)", 909)
COMPANY("Marinesoft Co. LTD", 510)
COMPANY("Mastervolt", 355)
COMPANY("MBW Technologies", 307)
COMPANY("McMurdo Group aka Orolia LTD", 573)
COMPANY("Mercury Marine", 144)
COMPANY("MMP", 1860)
COMPANY("Moritz Aerospace", 176)
COMPANY("Mystic Valley Communications", 198)
COMPANY("National Instruments Korea", 529)
COMPANY("Nautibus Electronic GmbH", 147)
COMPANY("Nautic-on", 911)
COMPANY("Navico", 275)
COMPANY("Navionics", 1852)
COMPANY("Naviop S.R.L.", 503)
COMPANY("Nexfour Solutions", 896)
COMPANY("Nobletec", 193)
COMPANY("NoLand Engineering", 517)
COMPANY("Northern Lights", 374)
COMPANY("Northstar Technologies", 1854)
COMPANY("NovAtel", 305)
COMPANY("Ocean Sat BV", 478)
COMPANY("Ocean Signal", 777)
COMPANY("Oceanvolt", 847)
COMPANY("Offshore Systems (UK) Ltd.", 161)
COMPANY("Onwa Marine", 532)
COMPANY("Parker Hannifin aka Village Marine Tech", 451)
COMPANY("Poly Planar", 781)
COMPANY("Prospec", 862)
COMPANY("Qwerty", 328)
COMPANY("Raymarine", 1851)
COMPANY("REAP Systems", 734)
COMPANY("Rhodan Marine Systems", 894)
COMPANY("Rockford Corp", 688)
COMPANY("Rolls Royce Marine", 370)
COMPANY("Rose Point Navigation Systems", 384)
COMPANY("Sailormade Marine Telemetry/Tetra Technology LTD", 235)
COMPANY("SamwonIT", 612)
COMPANY("SAN GIORGIO S.E.I.N", 460)
COMPANY("San Jose Technology", 580)
COMPANY("Sea Cross Marine AB", 471)
COMPANY("Sea Recovery", 285)
COMPANY("Seekeeper", 778)
COMPANY("Shenzhen Jiuzhou Himunication", 658)
COMPANY("Ship Module aka Customware", 595)
COMPANY("Simrad", 1857)
COMPANY("SI-TEX Marine Electronics", 470)
COMPANY("Sleipner Motor AS", 306)
COMPANY("Standard Horizon", 421)
COMPANY("Still Water Designs and Audio", 799)
COMPANY("Suzuki Motor Corporation", 586)
COMPANY("TeamSurv", 838)
COMPANY("Teleflex Marine (SeaStar Solutions)", 1850)
COMPANY("Thrane and Thrane", 351)
COMPANY("Tides Marine", 797)
COMPANY("Timbolier Industries", 962)
COMPANY("Tohatsu Co, JP", 431)
COMPANY("Transas USA", 518)
COMPANY("Trimble", 1856)
COMPANY("True Heading AB", 422)
COMPANY("Twin Disc", 80)
COMPANY("Undheim Systems", 824)
COMPANY("US Coast Guard", 591)
COMPANY("VDO (aka Continental-Corporation)", 443)
COMPANY("Vector Cantech", 1861)
COMPANY("Veethree Electronics & Marine", 466)
COMPANY("Vesper Marine Ltd", 504)
COMPANY("Victron Energy", 358)
COMPANY("Volvo Penta", 174)
COMPANY("Watcheye", 493)
COMPANY("Wema U.S.A dba KUS", 644)
COMPANY("Westerbeke", 154)
COMPANY("Woosung", 744)
COMPANY("Xantrex Technology Inc.", 168)
COMPANY("Xintex/Atena", 215)
COMPANY("Yacht Control", 583)
COMPANY("Yacht Devices", 717)
COMPANY("Yacht Monitoring Solutions", 233)
COMPANY("Yamaha Marine", 1862)
COMPANY("Yanmar Marine", 172)
COMPANY("ZF", 228)

