/* GENERATED BY keel FROM database/ - DO NOT EDIT.
*
* (C) 2009-2026, Kees Verruijt, Harlingen, The Netherlands.
* Part of CANboat; licensed under the Apache License, Version 2.0.
*/

Pgn pgnList[] = {
    {"0xE800-0xEEFF: Standardized single-frame addressed",
     59392,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 64, .resolution = 1.0}
     },
     .camelDescription = "0xe8000xeeffStandardizedSingleFrameAddressed",
     .fallback = true,
     .explanation = "Standardized PGNs in PDU1 (addressed) single-frame PGN range 0xE800 to 0xEE00 (59392 - 60928). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"ISO Acknowledgement",
     59392,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Control", .camelName = "control", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_CONTROL, .lookup.name = "ISO_CONTROL"},
      {.name = "Group Function", .camelName = "groupFunction", .fieldType = "UINT8", .resolution = 1.0},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 24, .resolution = 1.0},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24, .description = "Parameter Group Number of requested information"}
     },
     .camelDescription = "isoAcknowledgement",
     .interval = UINT16_MAX,
     .explanation = "This message is provided by ISO 11783 for a handshake mechanism between transmitting and receiving devices. This message is the possible response to acknowledge the reception of a 'normal broadcast' message or the response to a specific command to indicate compliance or failure."},

    {"ISO Request",
     59904,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoRequest",
     .interval = UINT16_MAX,
     .explanation = "As defined by ISO, this message has a data length of 3 bytes with no padding added to complete the single frame. The appropriate response to this message is based on the PGN being requested, and whether the receiver supports the requested PGN."},

    {"ISO Transport Protocol, Data Transfer",
     60160,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "SID", .camelName = "sid", .fieldType = "UINT8", .resolution = 1.0},
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 56, .resolution = 1.0}
     },
     .camelDescription = "isoTransportProtocolDataTransfer",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN represents a single packet of a multipacket message."},

    {"ISO Transport Protocol, Connection Management - Request To Send",
     60416,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Group Function Code", .camelName = "groupFunctionCode", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .unit = "=16", .description = "RTS", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_COMMAND, .lookup.name = "ISO_COMMAND"},
      {.name = "Message size", .camelName = "messageSize", .fieldType = "UINT16", .resolution = 1.0, .description = "bytes"},
      {.name = "Packets", .camelName = "packets", .fieldType = "UINT8", .resolution = 1.0, .description = "packets"},
      {.name = "Packets reply", .camelName = "packetsReply", .fieldType = "UINT8", .resolution = 1.0, .description = "packets sent in response to CTS"},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoTransportProtocolConnectionManagementRequestToSend",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this group function PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN's role in the transport process is to prepare the receiver for the fact that this sender wants to transmit a long message. The receiver will respond with CTS.",
     .url = "https://embeddedflakes.com/j1939-transport-protocol/"},

    {"ISO Transport Protocol, Connection Management - Clear To Send",
     60416,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Group Function Code", .camelName = "groupFunctionCode", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .unit = "=17", .description = "CTS", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_COMMAND, .lookup.name = "ISO_COMMAND"},
      {.name = "Max packets", .camelName = "maxPackets", .fieldType = "UINT8", .resolution = 1.0, .description = "Number of frames that can be sent before another CTS is required"},
      {.name = "Next SID", .camelName = "nextSid", .fieldType = "UINT8", .resolution = 1.0, .description = "Number of next frame to be transmitted"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoTransportProtocolConnectionManagementClearToSend",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this group function PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN's role in the transport process is to signal to the sender that the receive is ready to receive a number of frames.",
     .url = "https://embeddedflakes.com/j1939-transport-protocol/"},

    {"ISO Transport Protocol, Connection Management - End Of Message",
     60416,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Group Function Code", .camelName = "groupFunctionCode", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .unit = "=19", .description = "EOM", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_COMMAND, .lookup.name = "ISO_COMMAND"},
      {.name = "Total message size", .camelName = "totalMessageSize", .fieldType = "UINT16", .resolution = 1.0, .description = "bytes"},
      {.name = "Total number of frames received", .camelName = "totalNumberOfFramesReceived", .fieldType = "UINT8", .resolution = 1.0, .description = "Total number of of frames received"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 8, .resolution = 1.0},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoTransportProtocolConnectionManagementEndOfMessage",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this group function PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN's role in the transport process is to mark the end of the message.",
     .url = "https://embeddedflakes.com/j1939-transport-protocol/"},

    {"ISO Transport Protocol, Connection Management - Broadcast Announce",
     60416,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Group Function Code", .camelName = "groupFunctionCode", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .unit = "=32", .description = "BAM", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_COMMAND, .lookup.name = "ISO_COMMAND"},
      {.name = "Message size", .camelName = "messageSize", .fieldType = "UINT16", .resolution = 1.0, .description = "bytes"},
      {.name = "Packets", .camelName = "packets", .fieldType = "UINT8", .resolution = 1.0, .description = "frames"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 8, .resolution = 1.0},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoTransportProtocolConnectionManagementBroadcastAnnounce",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this group function PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN's role in the transport process is to announce a broadcast of a long message spanning multiple frames.",
     .url = "https://embeddedflakes.com/j1939-transport-protocol/"},

    {"ISO Transport Protocol, Connection Management - Abort",
     60416,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Group Function Code", .camelName = "groupFunctionCode", .fieldType = "LOOKUP", .size = 8, .resolution = 1.0, .unit = "=255", .description = "Abort", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupISO_COMMAND, .lookup.name = "ISO_COMMAND"},
      {.name = "Reason", .camelName = "reason", .fieldType = "BINARY", .size = 8, .resolution = 1.0},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 24, .resolution = 1.0},
      {.name = "PGN", .camelName = "pgn", .fieldType = "PGN", .size = 24}
     },
     .camelDescription = "isoTransportProtocolConnectionManagementAbort",
     .interval = UINT16_MAX,
     .explanation = "ISO 11783 defines this group function PGN as part of the Transport Protocol method used for transmitting messages that have 9 or more data bytes. This PGN's role in the transport process is to announce an abort of a long message spanning multiple frames.",
     .url = "https://embeddedflakes.com/j1939-transport-protocol/"},

    {"ISO Address Claim",
     60928,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Unique Number", .camelName = "uniqueNumber", .fieldType = "UNSIGNED_INTEGER", .size = 21, .resolution = 1.0, .description = "ISO Identity Number"},
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Device Instance Lower", .camelName = "deviceInstanceLower", .fieldType = "UNSIGNED_INTEGER", .size = 3, .resolution = 1.0, .description = "ISO ECU Instance"},
      {.name = "Device Instance Upper", .camelName = "deviceInstanceUpper", .fieldType = "UNSIGNED_INTEGER", .size = 5, .resolution = 1.0, .description = "ISO Function Instance"},
      {.name = "Device Function", .camelName = "deviceFunction", .fieldType = "INDIRECT_LOOKUP", .size = 8, .resolution = 1.0, .description = "ISO Function", .lookup.type = LOOKUP_TYPE_TRIPLET, LOOKUP_TRIPLET_MEMBER = lookupDEVICE_FUNCTION, .lookup.name = "DEVICE_FUNCTION", .lookup.val1Order = 7},
      {.name = "Spare", .camelName = "spare", .fieldType = "SPARE", .size = 1, .resolution = 1.0},
      {.name = "Device Class", .camelName = "deviceClass", .fieldType = "LOOKUP", .size = 7, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupDEVICE_CLASS, .lookup.name = "DEVICE_CLASS"},
      {.name = "System Instance", .camelName = "systemInstance", .fieldType = "UNSIGNED_INTEGER", .size = 4, .resolution = 1.0, .description = "ISO Device Class Instance"},
      {.name = "Industry Group", .camelName = "industryGroup", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Arbitrary address capable", .camelName = "arbitraryAddressCapable", .fieldType = "UNSIGNED_INTEGER", .size = 1, .resolution = 1.0, .description = "Field indicates whether the device is capable to claim arbitrary source address. Value is 1 for NMEA200 devices. Could be 0 for J1939 device claims"}
     },
     .camelDescription = "isoAddressClaim",
     .interval = UINT16_MAX,
     .explanation = "This network management message is used to claim network address, reply to devices requesting the claimed address, and to respond with device information (NAME) requested by the ISO Request or Complex Request Group Function. This PGN contains several fields that are requestable, either independently or in any combination."},

    {"0xEF00: Manufacturer Proprietary single-frame addressed",
     61184,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 2, .resolution = 1.0},
      {.name = "Industry Code", .camelName = "industryCode", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 48, .resolution = 1.0}
     },
     .camelDescription = "0xef00ManufacturerProprietarySingleFrameAddressed",
     .fallback = true,
     .explanation = "Manufacturer proprietary PGNs in PDU1 (addressed) single-frame PGN 0xEF00 (61184). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"0xF000-0xFEFF: Standardized single-frame non-addressed",
     61440,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 2, .resolution = 1.0},
      {.name = "Industry Code", .camelName = "industryCode", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 48, .resolution = 1.0}
     },
     .camelDescription = "0xf0000xfeffStandardizedSingleFrameNonAddressed",
     .fallback = true,
     .explanation = "PGNs in PDU2 (non-addressed) single-frame PGN range 0xF000 to 0xFEFF (61440 - 65279). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"Electronic Transmission Controller 1",
     61442,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Transmission Driveline Engaged", .camelName = "transmissionDrivelineEngaged", .fieldType = "UNSIGNED_INTEGER", .size = 2, .resolution = 1.0},
      {.name = "Torque Converter Lockup Engaged", .camelName = "torqueConverterLockupEngaged", .fieldType = "UNSIGNED_INTEGER", .size = 2, .resolution = 1.0},
      {.name = "Transmission Shift in Progress", .camelName = "transmissionShiftInProgress", .fieldType = "UNSIGNED_INTEGER", .size = 2, .resolution = 1.0},
      {.name = "Torque Converter Lockup Transition in Progress", .camelName = "torqueConverterLockupTransitionInProgress", .fieldType = "UNSIGNED_INTEGER", .size = 2, .resolution = 1.0},
      {.name = "Transmission Output Shaft Speed", .camelName = "transmissionOutputShaftSpeed", .fieldType = "ROTATION_UFIX16_RPM"},
      {.name = "Percent Clutch Slip", .camelName = "percentClutchSlip", .fieldType = "UINT8", .resolution = 1.0},
      {.name = "Engine Momentary Overspeed Enable", .camelName = "engineMomentaryOverspeedEnable", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupYES_NO, .lookup.name = "YES_NO"},
      {.name = "Progressive Shift Disable", .camelName = "progressiveShiftDisable", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupYES_NO, .lookup.name = "YES_NO"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 4, .resolution = 1.0},
      {.name = "Transmission Input Shaft Speed", .camelName = "transmissionInputShaftSpeed", .fieldType = "UINT16", .resolution = 1.0},
      {.name = "Source Address of Controlling Device for Transmission Control", .camelName = "sourceAddressOfControllingDeviceForTransmissionControl", .fieldType = "UINT8", .resolution = 1.0}
     },
     .camelDescription = "electronicTransmissionController1",
     .explanation = "J1939 ETC1 - Electronic Transmission Controller 1. Reports transmission status including driveline engagement, torque converter lockup, output/input shaft speeds, and clutch slip."},

    {"ECU #2",
     61443,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 8, .resolution = 1.0},
      {.name = "Throttle Lever", .camelName = "throttleLever", .fieldType = "PERCENTAGE_UINT8", .resolution = 0.4},
      {.name = "Reserved", .camelName = "reserved3", .fieldType = "RESERVED", .size = 48, .resolution = 1.0}
     },
     .camelDescription = "ecu2"},

    {"ECU #1",
     61444,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 24, .resolution = 1.0},
      {.name = "Engine RPM", .camelName = "engineRpm", .fieldType = "ROTATION_UFIX16_RPM_HIGHRES"},
      {.name = "Reserved", .camelName = "reserved3", .fieldType = "RESERVED", .size = 24, .resolution = 1.0}
     },
     .camelDescription = "ecu1"},

    {"Bus #1 Phase C Basic AC Quantities",
     65001,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0}
     },
     .camelDescription = "bus1PhaseCBasicAcQuantities"},

    {"Bus #1 Phase B Basic AC Quantities",
     65002,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0}
     },
     .camelDescription = "bus1PhaseBBasicAcQuantities"},

    {"Bus #1 Phase A Basic AC Quantities",
     65003,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0}
     },
     .camelDescription = "bus1PhaseABasicAcQuantities"},

    {"Bus #1 Average Basic AC Quantities",
     65004,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0}
     },
     .camelDescription = "bus1AverageBasicAcQuantities"},

    {"Utility Total AC Energy",
     65005,
     PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Total Energy Export", .camelName = "totalEnergyExport", .fieldType = "ENERGY_UINT32", .resolution = 1.0},
      {.name = "Total Energy Import", .camelName = "totalEnergyImport", .fieldType = "ENERGY_UINT32", .resolution = 1.0}
     },
     .camelDescription = "utilityTotalAcEnergy"},

    {"Utility Phase C AC Reactive Power",
     65006,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_UINT16_VAR"},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 30, .resolution = 1.0}
     },
     .camelDescription = "utilityPhaseCAcReactivePower"},

    {"Utility Phase C AC Power",
     65007,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "utilityPhaseCAcPower"},

    {"Utility Phase C Basic AC Quantities",
     65008,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "utilityPhaseCBasicAcQuantities"},

    {"Utility Phase B AC Reactive Power",
     65009,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_UINT16_VAR"},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 30, .resolution = 1.0}
     },
     .camelDescription = "utilityPhaseBAcReactivePower"},

    {"Utility Phase B AC Power",
     65010,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "utilityPhaseBAcPower"},

    {"Utility Phase B Basic AC Quantities",
     65011,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "utilityPhaseBBasicAcQuantities"},

    {"Utility Phase A AC Reactive Power",
     65012,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "utilityPhaseAAcReactivePower"},

    {"Utility Phase A AC Power",
     65013,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "utilityPhaseAAcPower"},

    {"Utility Phase A Basic AC Quantities",
     65014,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "utilityPhaseABasicAcQuantities"},

    {"Utility Total AC Reactive Power",
     65015,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "utilityTotalAcReactivePower"},

    {"Utility Total AC Power",
     65016,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "utilityTotalAcPower"},

    {"Utility Average Basic AC Quantities",
     65017,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "utilityAverageBasicAcQuantities"},

    {"Generator Total AC Energy",
     65018,
     PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Total Energy Export", .camelName = "totalEnergyExport", .fieldType = "ENERGY_UINT32", .resolution = 1.0},
      {.name = "Total Energy Import", .camelName = "totalEnergyImport", .fieldType = "ENERGY_UINT32", .resolution = 1.0}
     },
     .camelDescription = "generatorTotalAcEnergy"},

    {"Generator Phase C AC Reactive Power",
     65019,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "generatorPhaseCAcReactivePower"},

    {"Generator Phase C AC Power",
     65020,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true}
     },
     .camelDescription = "generatorPhaseCAcPower"},

    {"Generator Phase C Basic AC Quantities",
     65021,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "generatorPhaseCBasicAcQuantities"},

    {"Generator Phase B AC Reactive Power",
     65022,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "generatorPhaseBAcReactivePower"},

    {"Generator Phase B AC Power",
     65023,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "generatorPhaseBAcPower"},

    {"Generator Phase B Basic AC Quantities",
     65024,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "generatorPhaseBBasicAcQuantities"},

    {"Generator Phase A AC Reactive Power",
     65025,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "generatorPhaseAAcReactivePower"},

    {"Generator Phase A AC Power",
     65026,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "generatorPhaseAAcPower"},

    {"Generator Phase A Basic AC Quantities",
     65027,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "generatorPhaseABasicAcQuantities"},

    {"Generator Total AC Reactive Power",
     65028,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Reactive Power", .camelName = "reactivePower", .fieldType = "POWER_FIX32_VAR_OFFSET", .hasSign = true},
      {.name = "Power factor", .camelName = "powerFactor", .fieldType = "UINT16", .resolution = 6.10352e-5, .unit = "Cos Phi", .rangeMin = 0.0, .rangeMax = 3.999755859375},
      {.name = "Power Factor Lagging", .camelName = "powerFactorLagging", .fieldType = "LOOKUP", .size = 2, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupPOWER_FACTOR, .lookup.name = "POWER_FACTOR"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 14, .resolution = 1.0}
     },
     .camelDescription = "generatorTotalAcReactivePower"},

    {"Generator Total AC Power",
     65029,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Real Power", .camelName = "realPower", .fieldType = "POWER_FIX32_OFFSET", .hasSign = true},
      {.name = "Apparent Power", .camelName = "apparentPower", .fieldType = "POWER_FIX32_VA_OFFSET", .hasSign = true}
     },
     .camelDescription = "generatorTotalAcPower"},

    {"Generator Average Basic AC Quantities",
     65030,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     {
      {.name = "Line-Line AC RMS Voltage", .camelName = "lineLineAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "Line-Neutral AC RMS Voltage", .camelName = "lineNeutralAcRmsVoltage", .fieldType = "VOLTAGE_UFIX16_V"},
      {.name = "AC Frequency", .camelName = "acFrequency", .fieldType = "FREQUENCY_UFIX16", .resolution = 0.0078125},
      {.name = "AC RMS Current", .camelName = "acRmsCurrent", .fieldType = "CURRENT_UFIX16_A"}
     },
     .camelDescription = "generatorAverageBasicAcQuantities"},

    {"Active Trouble Codes",
     65226,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Malfunction Lamp Status", .camelName = "malfunctionLampStatus", .fieldType = "BINARY", .size = 2, .resolution = 1.0, .description = "Fault Lamps"},
      {.name = "Red Stop Lamp Status", .camelName = "redStopLampStatus", .fieldType = "BINARY", .size = 2, .resolution = 1.0, .description = "Fault Lamps"},
      {.name = "Amber Warning Lamp Status", .camelName = "amberWarningLampStatus", .fieldType = "BINARY", .size = 2, .resolution = 1.0, .description = "Fault Lamps"},
      {.name = "Protect Lamp Status", .camelName = "protectLampStatus", .fieldType = "BINARY", .size = 2, .resolution = 1.0, .description = "Fault Lamps"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 8, .resolution = 1.0},
      {.name = "SPN", .camelName = "spn", .fieldType = "BINARY", .size = 19, .resolution = 1.0, .description = "Suspect Parameter Number"},
      {.name = "FMI", .camelName = "fmi", .fieldType = "BINARY", .size = 5, .resolution = 1.0, .description = "Fault Mode Indicator"},
      {.name = "CM", .camelName = "cm", .fieldType = "BINARY", .size = 1, .resolution = 1.0, .description = "SPN Conversion Method"},
      {.name = "OC", .camelName = "oc", .fieldType = "BINARY", .size = 7, .resolution = 1.0, .description = "Occurance Count"}
     },
     .camelDescription = "activeTroubleCodes",
     .repeatingCount1 = 4,
     .repeatingStart1 = 6,
     .repeatingField1 = 255},

    {"ISO Commanded Address",
     65240,
     PACKET_COMPLETE,
     PACKET_ISO_TP,
     {
      {.name = "Unique Number", .camelName = "uniqueNumber", .fieldType = "BINARY", .size = 21, .resolution = 1.0, .description = "ISO Identity Number"},
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .unit = "Manufacturer Code", .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Device Instance Lower", .camelName = "deviceInstanceLower", .fieldType = "UNSIGNED_INTEGER", .size = 3, .resolution = 1.0, .description = "ISO ECU Instance"},
      {.name = "Device Instance Upper", .camelName = "deviceInstanceUpper", .fieldType = "UNSIGNED_INTEGER", .size = 5, .resolution = 1.0, .description = "ISO Function Instance"},
      {.name = "Device Function", .camelName = "deviceFunction", .fieldType = "INDIRECT_LOOKUP", .size = 8, .resolution = 1.0, .description = "ISO Function", .lookup.type = LOOKUP_TYPE_TRIPLET, LOOKUP_TRIPLET_MEMBER = lookupDEVICE_FUNCTION, .lookup.name = "DEVICE_FUNCTION", .lookup.val1Order = 7},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 1, .resolution = 1.0},
      {.name = "Device Class", .camelName = "deviceClass", .fieldType = "LOOKUP", .size = 7, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupDEVICE_CLASS, .lookup.name = "DEVICE_CLASS"},
      {.name = "System Instance", .camelName = "systemInstance", .fieldType = "UNSIGNED_INTEGER", .size = 4, .resolution = 1.0, .description = "ISO Device Class Instance"},
      {.name = "Industry Code", .camelName = "industryCode", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Reserved", .camelName = "reserved10", .fieldType = "RESERVED", .size = 1, .resolution = 1.0},
      {.name = "New Source Address", .camelName = "newSourceAddress", .fieldType = "UINT8", .resolution = 1.0}
     },
     .camelDescription = "isoCommandedAddress"},

    {"Engine Temp #1",
     65262,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Engine Coolant Temp", .camelName = "engineCoolantTemp", .fieldType = "TEMPERATURE_UINT8_OFFSET"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 56, .resolution = 1.0}
     },
     .camelDescription = "engineTemp1"},

    {"Fuel Economy",
     65266,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 48, .resolution = 1.0},
      {.name = "Throttle Position", .camelName = "throttlePosition", .fieldType = "PERCENTAGE_UINT8", .resolution = 0.4},
      {.name = "Reserved", .camelName = "reserved3", .fieldType = "RESERVED", .size = 8, .resolution = 1.0}
     },
     .camelDescription = "fuelEconomy"},

    {"Ambient Conditions",
     65269,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Barometric Pressure", .camelName = "barometricPressure", .fieldType = "PRESSURE_UINT8_KPA"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 56, .resolution = 1.0}
     },
     .camelDescription = "ambientConditions"},

    {"Inlet/Exhaust Conditions",
     65270,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 16, .resolution = 1.0},
      {.name = "Intake Manifold Temp", .camelName = "intakeManifoldTemp", .fieldType = "TEMPERATURE_UINT8_OFFSET"},
      {.name = "Air Inlet Pressure", .camelName = "airInletPressure", .fieldType = "PRESSURE_UINT8_2KPA"},
      {.name = "Reserved", .camelName = "reserved4", .fieldType = "RESERVED", .size = 32, .resolution = 1.0}
     },
     .camelDescription = "inletExhaustConditions"},

    {"Vehicle Electrical Power",
     65271,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 32, .resolution = 1.0},
      {.name = "Battery Voltage", .camelName = "batteryVoltage", .fieldType = "VOLTAGE_UFIX16_50MV"},
      {.name = "Reserved", .camelName = "reserved3", .fieldType = "RESERVED", .size = 16, .resolution = 1.0}
     },
     .camelDescription = "vehicleElectricalPower"},

    {"0xFF00-0xFFFF: Manufacturer Proprietary single-frame non-addressed",
     65280,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_SINGLE,
     {
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 2, .resolution = 1.0},
      {.name = "Industry Code", .camelName = "industryCode", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 48, .resolution = 1.0}
     },
     .camelDescription = "0xff000xffffManufacturerProprietarySingleFrameNonAddressed",
     .fallback = true,
     .explanation = "Manufacturer proprietary PGNs in PDU2 (non-addressed) single-frame PGN range 0xFF00 to 0xFFFF (65280 - 65535). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"0x1ED00 - 0x1EE00: Standardized fast-packet addressed",
     126208,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN | PACKET_LOOKUPS_UNKNOWN,
     PACKET_FAST,
     {
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 1784, .resolution = 1.0}
     },
     .camelDescription = "0x1ed000x1ee00StandardizedFastPacketAddressed",
     .fallback = true,
     .explanation = "Standardized PGNs in PDU1 (addressed) fast-packet PGN range 0x1ED00 to 0x1EE00 (65536 - 126464). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"0x1EF00-0x1EFFF: Manufacturer Proprietary fast-packet addressed",
     126720,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_FAST,
     {
      {.name = "Manufacturer Code", .camelName = "manufacturerCode", .fieldType = "LOOKUP", .size = 11, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupMANUFACTURER_CODE, .lookup.name = "MANUFACTURER_CODE"},
      {.name = "Reserved", .camelName = "reserved", .fieldType = "RESERVED", .size = 2, .resolution = 1.0},
      {.name = "Industry Code", .camelName = "industryCode", .fieldType = "LOOKUP", .size = 3, .resolution = 1.0, .lookup.type = LOOKUP_TYPE_PAIR, LOOKUP_PAIR_MEMBER = lookupINDUSTRY_CODE, .lookup.name = "INDUSTRY_CODE"},
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 1768, .resolution = 1.0}
     },
     .camelDescription = "0x1ef000x1efffManufacturerProprietaryFastPacketAddressed",
     .fallback = true,
     .explanation = "Manufacturer Proprietary PGNs in PDU1 (addressed) fast-packet PGN range 0x1EF00 to 0x1EFFF (126720 - 126975). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"0x1F000-0x1FEFF: Standardized mixed single/fast packet non-addressed",
     126976,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_MIXED,
     {
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 1784, .resolution = 1.0}
     },
     .camelDescription = "0x1f0000x1feffStandardizedMixedSingleFastPacketNonAddressed",
     .fallback = true,
     .explanation = "Standardized PGNs in PDU2 (non-addressed) mixed single/fast packet PGN range 0x1F000 to 0x1FEFF (126976 - 130815). When this is shown during analysis it means the PGN is not reverse engineered yet."},

    {"0x1FF00-0x1FFFF: Manufacturer Specific fast-packet non-addressed",
     130816,
     PACKET_FIELDS_UNKNOWN | PACKET_FIELD_LENGTHS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN,
     PACKET_FAST,
     {
      {.name = "Data", .camelName = "data", .fieldType = "BINARY", .size = 1784, .resolution = 1.0}
     },
     .camelDescription = "0x1ff000x1ffffManufacturerSpecificFastPacketNonAddressed",
     .fallback = true,
     .explanation = "This definition is used for Manufacturer Specific PGNs in PDU2 (non-addressed) fast-packet PGN range 0x1FF00 to 0x1FFFF (130816 - 131071). When this is shown during analysis it means the PGN is not reverse engineered yet."}
};
