/* GENERATED BY keel FROM database/ - DO NOT EDIT.
*
* (C) 2009-2026, Kees Verruijt, Harlingen, The Netherlands.
* Part of CANboat; licensed under the Apache License, Version 2.0.
*/

static const PhysicalQuantity ELECTRICAL_CURRENT = {
    .name = "ELECTRICAL_CURRENT",
    .description = "Electrical current",
    .abbreviation = "A",
    .unit = "Ampere",
    .url = "https://en.wikipedia.org/wiki/Electric_current",
};

static const PhysicalQuantity ELECTRICAL_CHARGE = {
    .name = "ELECTRICAL_CHARGE",
    .description = "Electrical charge",
    .abbreviation = "C",
    .unit = "Coulomb",
    .url = "https://en.wikipedia.org/wiki/Electric_charge",
};

static const PhysicalQuantity ELECTRICAL_ENERGY = {
    .name = "ELECTRICAL_ENERGY",
    .description = "Electrical energy",
    .comment = "The amount of electricity used or stored. The base unit used in NMEA 2000 is the Kilo Watt Hour (kWh) which is equivalent to 3.6e6 J (Joules).",
    .abbreviation = "kWh",
    .unit = "Kilo Watt Hour",
    .url = "https://en.wikipedia.org/wiki/Electrical_energy",
};

static const PhysicalQuantity ELECTRICAL_POWER = {
    .name = "ELECTRICAL_POWER",
    .description = "Electrical power",
    .comment = "The amount of energy transferred or converted per unit time.",
    .abbreviation = "W",
    .unit = "Watt",
    .url = "https://en.wikipedia.org/wiki/Electrical_power",
};

static const PhysicalQuantity ELECTRICAL_APPARENT_POWER = {
    .name = "ELECTRICAL_APPARENT_POWER",
    .description = "AC apparent power",
    .comment = "The amount of power transferred where the current and voltage are in phase.",
    .abbreviation = "VA",
    .unit = "Volt Ampere",
    .url = "https://en.wikipedia.org/wiki/Volt-ampere",
};

static const PhysicalQuantity ELECTRICAL_REACTIVE_POWER = {
    .name = "ELECTRICAL_REACTIVE_POWER",
    .description = "AC reactive power",
    .comment = "The amount of power transferred where the current and voltage are not in phase.",
    .abbreviation = "VAR",
    .unit = "Volt Ampere Reactive",
    .url = "https://en.wikipedia.org/wiki/Volt-ampere#Reactive",
};

static const PhysicalQuantity POTENTIAL_DIFFERENCE = {
    .name = "POTENTIAL_DIFFERENCE",
    .description = "Potential difference",
    .abbreviation = "V",
    .unit = "Volt",
    .url = "https://en.wikipedia.org/wiki/Voltage",
};

static const PhysicalQuantity POWER_FACTOR = {
    .name = "POWER_FACTOR",
    .description = "Power Factor",
    .comment = "Used in AC circuits only, the ratio of the real power absorbed by the load to the apparent power flowing in the circuit. If less than one, the voltage and current are not in phase.",
    .abbreviation = "Cos Phi",
    .unit = "Cos(Phi)",
    .url = "https://en.wikipedia.org/wiki/Power_factor",
};

static const PhysicalQuantity LENGTH = {
    .name = "LENGTH",
    .description = "Length",
    .comment = "The physical size in one dimension of an object.",
    .abbreviation = "m",
    .unit = "Meter",
    .url = "https://en.wikipedia.org/wiki/Length",
};

static const PhysicalQuantity DISTANCE = {
    .name = "DISTANCE",
    .description = "Distance",
    .comment = "The amount of separation between two objects.",
    .abbreviation = "m",
    .unit = "meter",
    .url = "https://en.wikipedia.org/wiki/Distance",
};

static const PhysicalQuantity SPEED = {
    .name = "SPEED",
    .description = "Speed",
    .comment = "The velocity, or length per unit of time.",
    .abbreviation = "m/s",
    .unit = "meter per second",
    .url = "https://en.wikipedia.org/wiki/Speed",
};

static const PhysicalQuantity ANGLE = {
    .name = "ANGLE",
    .description = "Angle",
    .comment = "All standardized PGNs seen so far all use radians, but some manufacturer specific PGNs use degrees (deg).",
    .abbreviation = "rad",
    .unit = "radian",
    .url = "https://en.wikipedia.org/wiki/Angle",
};

static const PhysicalQuantity ANGULAR_VELOCITY = {
    .name = "ANGULAR_VELOCITY",
    .description = "Angular velocity",
    .comment = "The speed at which a measured angle changes",
    .abbreviation = "rad/s",
    .unit = "radians per second",
    .url = "https://en.wikipedia.org/wiki/Angular_velocity",
};

static const PhysicalQuantity VOLUME = {
    .name = "VOLUME",
    .description = "Volume",
    .comment = "A measure of occupied three-dimensional space.",
    .abbreviation = "L",
    .unit = "liter",
    .url = "https://en.wikipedia.org/wiki/Volume",
};

static const PhysicalQuantity VOLUMETRIC_FLOW = {
    .name = "VOLUMETRIC_FLOW",
    .description = "Volumetric flow",
    .comment = "The volume of fluid which passes per unit time.",
    .abbreviation = "L/h",
    .unit = "liter per hour",
    .url = "https://en.wikipedia.org/wiki/Volumetric_flow_rate",
};

static const PhysicalQuantity MAGNETIC_FIELD = {
    .name = "MAGNETIC_FIELD",
    .description = "Magnetic field",
    .abbreviation = "T",
    .unit = "Tesla",
    .url = "https://en.wikipedia.org/wiki/Magnetic_field",
};

static const PhysicalQuantity FREQUENCY = {
    .name = "FREQUENCY",
    .description = "Frequency",
    .abbreviation = "Hz",
    .unit = "Hertz",
    .url = "https://en.wikipedia.org/wiki/Radio_frequency",
};

static const PhysicalQuantity DATE = {
    .name = "DATE",
    .description = "Date",
    .comment = "A calendar date is a reference to a particular day in time, in NMEA 2000 expressed as the number of days since 1970-01-01 (UNIX epoch).",
    .abbreviation = "d",
    .unit = "days",
    .url = "https://en.wikipedia.org/wiki/Calendar_date",
};

static const PhysicalQuantity TIME = {
    .name = "TIME",
    .description = "Time",
    .comment = "Time is what clocks measure. We use time to place events in sequence one after the other, and we use time to compare how long events last. Absolute times in NMEA2000 are expressed as seconds since midnight(in an undefined timezone)",
    .abbreviation = "s",
    .unit = "Second",
    .url = "https://en.wikipedia.org/wiki/Time",
};

static const PhysicalQuantity DURATION = {
    .name = "DURATION",
    .description = "Duration of an event or interval between two points in time",
    .abbreviation = "s",
    .unit = "Second",
};

static const PhysicalQuantity GEOGRAPHICAL_LATITUDE = {
    .name = "GEOGRAPHICAL_LATITUDE",
    .description = "Geographical latitude",
    .comment = "Combined with a geographical longitude the two fields form a unique point on earth, when height is disregarded.",
    .abbreviation = "deg",
    .unit = "degree",
    .url = "https://en.wikipedia.org/wiki/Geographic_coordinate_system",
};

static const PhysicalQuantity GEOGRAPHICAL_LONGITUDE = {
    .name = "GEOGRAPHICAL_LONGITUDE",
    .description = "Geographical longitude",
    .comment = "Combined with a geographical latitude the two fields form a unique point on earth, when height is disregarded.",
    .abbreviation = "deg",
    .unit = "degree",
    .url = "https://en.wikipedia.org/wiki/Geographic_coordinate_system",
};

static const PhysicalQuantity TEMPERATURE = {
    .name = "TEMPERATURE",
    .description = "Temperature",
    .abbreviation = "K",
    .unit = "Kelvin",
    .url = "https://en.wikipedia.org/wiki/Temperature",
};

static const PhysicalQuantity PRESSURE = {
    .name = "PRESSURE",
    .description = "Pressure",
    .abbreviation = "Pa",
    .unit = "Pascal",
    .url = "https://en.wikipedia.org/wiki/Pressure",
};

static const PhysicalQuantity PRESSURE_RATE = {
    .name = "PRESSURE_RATE",
    .description = "Pressure rate",
    .comment = "How the pressure changes over time.",
    .abbreviation = "Pa/hr",
    .unit = "Pascal per hour",
    .url = "https://en.wikipedia.org/wiki/Pressure",
};

static const PhysicalQuantity CONCENTRATION = {
    .name = "CONCENTRATION",
    .description = "Concentration of one substance in another, in this marine context usually the amount of salts in water",
    .abbreviation = "ppm",
    .unit = "parts per million",
    .url = "https://www.engineeringtoolbox.com/water-salinity-d_1251.html",
};

static const PhysicalQuantity DIMENSIONLESS_RATIO = {
    .name = "DIMENSIONLESS_RATIO",
    .description = "Dimensionless ratio",
    .comment = "A ratio of two quantities with the same dimension, yielding a unitless number. Includes percentages, eccentricity (m/m), clock drift (s/s), and similar.",
    .abbreviation = "ratio",
    .unit = "ratio",
    .url = "https://en.wikipedia.org/wiki/Dimensionless_quantity",
};

static const PhysicalQuantity SQUARE_ROOT_LENGTH = {
    .name = "SQUARE_ROOT_LENGTH",
    .description = "Square root of length",
    .comment = "Used in GPS/GNSS almanac data for the square root of the semi-major axis of satellite orbits.",
    .abbreviation = "sqrt(m)",
    .unit = "sqrt(m)",
    .url = "https://en.wikipedia.org/wiki/Semi-major_and_semi-minor_axes",
};

static const PhysicalQuantity SIGNAL_STRENGTH = {
    .name = "SIGNAL_STRENGTH",
    .description = "Signal strength expressed in dB with respect to 1 uV/m",
    .abbreviation = "dB",
    .unit = "decibel",
    .url = "https://en.wikipedia.org/wiki/Signal_strength_in_telecommunications",
};

static const PhysicalQuantity SIGNAL_TO_NOISE_RATIO = {
    .name = "SIGNAL_TO_NOISE_RATIO",
    .description = "Signal-to-noise ratio",
    .abbreviation = "dB",
    .unit = "decibel",
    .url = "https://en.wikipedia.org/wiki/Signal-to-noise_ratio",
};

const PhysicalQuantity *const PhysicalQuantityList[] = {
    &ELECTRICAL_CURRENT,
    &ELECTRICAL_CHARGE,
    &ELECTRICAL_ENERGY,
    &ELECTRICAL_POWER,
    &ELECTRICAL_APPARENT_POWER,
    &ELECTRICAL_REACTIVE_POWER,
    &POTENTIAL_DIFFERENCE,
    &POWER_FACTOR,
    &LENGTH,
    &DISTANCE,
    &SPEED,
    &ANGLE,
    &ANGULAR_VELOCITY,
    &VOLUME,
    &VOLUMETRIC_FLOW,
    &MAGNETIC_FIELD,
    &FREQUENCY,
    &DATE,
    &TIME,
    &DURATION,
    &GEOGRAPHICAL_LATITUDE,
    &GEOGRAPHICAL_LONGITUDE,
    &TEMPERATURE,
    &PRESSURE,
    &PRESSURE_RATE,
    &CONCENTRATION,
    &DIMENSIONLESS_RATIO,
    &SQUARE_ROOT_LENGTH,
    &SIGNAL_STRENGTH,
    &SIGNAL_TO_NOISE_RATIO,
    NULL,
};
