#!/usr/bin/env python3
#
# (C) 2009-2025, Kees Verruijt, Harlingen, The Netherlands.
#
# This file is part of CANboat.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generate fastpacket-table.h from canboat.json.
#
# A received CAN frame only tells us its PGN, never whether that PGN is
# transported as a single frame or as a fast-packet sequence. For most
# PGNs the range alone decides this (see ALLOW_PGN_FAST_PACKET /
# ALLOW_PGN_SINGLE_FRAME in common.h), but the range 0x1F000..0x1FFFF
# is "mixed": both single-frame and fast-packet PGNs live there. For
# that range we need a per-PGN lookup, which we derive here at build
# time straight from the PGN database so it always tracks the spec.
#
# Usage: gen-fastpacket-table.py <canboat.json> <output.h>

import json
import sys

MIXED_START = 0x1F000
MIXED_END = 0x20000  # exclusive; table covers 0x1F000..0x1FFFF (0x1000 entries)
MIXED_SIZE = MIXED_END - MIXED_START
PROPRIETARY_START = 0x1FF00  # 0x1FF00..0x1FFFF defaults to fast-packet


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("Usage: gen-fastpacket-table.py <canboat.json> <output.h>\n")
        return 1

    with open(sys.argv[1]) as f:
        db = json.load(f)

    # Default: the manufacturer-proprietary tail (0x1FF00..0x1FFFF) is
    # fast-packet, the standardized part defaults to single frame. The
    # explicit PGN definitions below override both where they differ.
    fast = [pgn >= PROPRIETARY_START for pgn in range(MIXED_START, MIXED_END)]

    for p in db["PGNs"]:
        pgn = p["PGN"]
        if not (MIXED_START <= pgn < MIXED_END):
            continue
        if p.get("Fallback"):  # range fallbacks ("Mixed"/proprietary), not a real PGN
            continue
        fast[pgn - MIXED_START] = p["Type"] == "Fast"

    version = db.get("Version", "unknown")
    with open(sys.argv[2], "w") as out:
        out.write("/* Generated by gen-fastpacket-table.py from canboat.json v%s. */\n" % version)
        out.write("/* Do not edit; regenerate with `make fastpacket-table.h`.   */\n\n")
        out.write("#ifndef FASTPACKET_TABLE_H_INCLUDED\n")
        out.write("#define FASTPACKET_TABLE_H_INCLUDED\n\n")
        out.write("#define FASTPACKET_MIXED_START 0x%05xU\n" % MIXED_START)
        out.write("#define FASTPACKET_MIXED_END 0x%05xU\n\n" % MIXED_END)
        out.write("/* 1 = fast-packet, 0 = single-frame, for PGNs 0x%05x..0x%05x. */\n"
                  % (MIXED_START, MIXED_END - 1))
        out.write("static const unsigned char FASTPACKET_MIXED[0x%x] = {" % MIXED_SIZE)
        for i, v in enumerate(fast):
            if i % 32 == 0:
                out.write("\n  ")
            out.write("1," if v else "0,")
        out.write("\n};\n\n")
        out.write("#endif\n")

    sys.stderr.write("gen-fastpacket-table.py: %d fast-packet PGNs in mixed range\n" % sum(fast))
    return 0


if __name__ == "__main__":
    sys.exit(main())
