#!/usr/bin/php
<?php
#
# A very limited script engine that sends and receives CAN messages.
#
# (C) 2009-2021, Kees Verruijt, Harlingen, The Netherlands.
#  
# This file is part of CANboat.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

require_once('canboat-default.inc');

$format = strtoupper(getCanboatDefault('WRITE_FORMAT', 'CANBOAT'));
$command = getCanboatDefault('WRITE_COMMAND', null);

if ($format == 'CANBOAT')
{
  $send_product_info="2012-06-17-15:02:11.000,6,59904,0,255,3,14,f0,01\n"; # ./send-message/format-message 255 request_pgn 126996
  $send_config_info="2012-06-17-15:02:11.000,6,59904,0,255,3,16,f0,01\n";  # ./send-message/format-message 255 request_pgn 126998
} 
elseif ($format == 'YDWG')
{
  $send_product_info="18EAFF00 14 f0 01\r\n"; # ./send-message/format-message 255 request_pgn 126996
  $send_config_info="18EAFF00 16 f0 01\r\n";  # ./send-message/format-message 255 request_pgn 126998
}
else
{
  die("Unknown WRITE_FORMAT='$format' in '/etc/default/canboat'\n");
}


function value($arr, $key, $default = null)
{
  if (array_key_exists($key, $arr))
  {
    return $arr[$key];
  }
  return $default;
}

if ($command)
{
  $fd = popen($command, 'r');
  fwrite($fd, $send_product_info);
  fclose($fd);
}

$errno = 0;
$errstr = '';
$n2k = @fsockopen('localhost', 2597, $errno, $errstr, 15);
if (!$n2k)
{
  echo "Cannot connect to N2KD: $errstr\n";
  exit(1);
}

#
# Ask for device list
#

if (!$command) // then send to n2kd
{
  fwrite($n2k, $send_product_info);
}
$s = '';
while (!feof($n2k))
{
  $s .= fgets($n2k, 1024);
}
fclose($n2k);
$data = json_decode($s, true);
if (!is_array($data) || !is_array($data[126996]))
{
  echo "No product information received.\n";
  if ($debug)
  {
    print_r($data);
  }
  exit(1);
}
$devices = $data[126996];
foreach ($devices as $src => $device)
{
  if (!is_array($device))
  {
    echo "$device:\n";
    continue;
  }
  $id      = $device['fields']['Model ID'];
  $version = $device['fields']['Software Version Code'];
  $model   = $device['fields']['Model Version'];
  $n2kver  = value($device['fields'], 'NMEA 2000 Version', '?');

  if (preg_match('/(\d{1,3})_\d+/', $src, $matches))
  {
    $src = $matches[1];
  }

  printf("%3d | %-32.32s | %-1.32s | %-1.32s | %s\n", $src, $id, $version, $model, $n2kver);
}

?>
