pgn: 130835
id: simnetSetEngineAndTankConfiguration
description: 'Simnet: Set Engine and Tank Configuration'
type: Fast
variantOrder: 2
missing:
- Fields
- FieldLengths
- Resolution
- SampleData
fields:
- id: manufacturerCode
  name: Manufacturer Code
  type: LOOKUP
  bits: 11
  description: Simrad
  match: 1857
  lookup: MANUFACTURER_CODE
- id: reserved
  name: Reserved
  type: RESERVED
  bits: 2
- id: industryCode
  name: Industry Code
  type: LOOKUP
  bits: 3
  description: Marine Industry
  match: 4
  lookup: INDUSTRY_CODE
